const Constants = {
	BASE_URL : "https://tricproject.azurewebsites.net/",
	SOCKET_URL: "https://tricproject.azurewebsites.net/ws-message",
	//BASE_URL: "http://localhost:8080/",
	//SOCKET_URL: "http://localhost:8080/ws-message",

	/* LABELS */
	APP_TITLE: "TRIC",
	JOIN_BUTTON: "Join",
	CREATE_USER_FIELD: "Create User",
	LOGIN_USER_FIELD: "Login User",
	USERNAME_FIELD: "Username",
	PASSWORD_FIELD: "Password",
	AVATAR_FIELD: "Select an avatar",
	SUBMIT_BUTTON: "Submit",
	QUESTION_FIELD:	"Question",
	VOTE_RESULT_FIELD: "Vote Result",
	CONFIRM_BUTTON: "Confirm",
	WAITING_PROMPT_RESULT: "Gathering votes...",
	WAITING_PROMPT_BEGIN: "Waiting for the first question...",
	DOWNLOAD :"DOWNLOAD",
	FINAL_RESULT_FIELD: "YOUR DIGITAL PROFILE" ,
	USER_RESPONSE : "Your response",
	FINAL_RESULT_BUTTON:" Show Final Result",
	RESULT_FIELD: "Result",
	RESULT_BUTTON : "Show Result",
	QUESTION_BUTTON: "Show Question",
	START_BUTTON: "Start",
	END_BUTTON: "End Session",
	PAGE_404_MESSAGE: "There's nothing here: 404!",
	ADMIN_TITLE: "Admin",
	NO_ACTIVE_PLAY: "No ongoing play right now.",
	MORE_INFO_TEXT: "Find more about us and when the next play will be here: ",
	MORE_INFO_LINK: "https://www.humanlab.studio/index.html",
	EDIT_CONTRIBUTORS: "Edit Contributors",
	EDIT_QUESTIONS: "Edit Questions",
	NEW_QUESTION_TITLE: "New Question",
	SAVE_BUTTON: "Save",
	QUESTION_LIST_TITLE: "Questions",
	ONLINE_USERS: "Online users:",
	ON_SCREEN_FIELD: "is on screen...",
	TIME_REMANING: "seconds remaining",
	TIME_FOR: "Time for Question",
	HUMANLAB: "HumanLab",
	QUESTIONS_FIELD: "Questions",
	ALL_QUESTIONS_FIELD: "Show All Questions",
};

export default Constants;
